### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by nikoe** [mcela/financeapp#1]
Heippa,

Aiheesi vaikuttaa hyvältä, saat siitä varmasti tarpeeksi laajan arvosanaa 5 varten.

Dokumentaatio on hyvin tehty, siitä ei oikeen ole mitään sanottavaa. Hyvää työtä sen suhteen :+1: 

Projekti on hyvin järjestetty ja kansiorakenne on selkeä, huomaan että olet ennenkin tehnyt devausprojekteja. Koodisi on hyvin kommentoitua siitä kanssa propsit, koska moni ei kommentoi noin hyvin kuin sinä. PHP ei ohjelmointikielenä ole minulle tutuimpia, joten en oikein osaa sanoa onko se ns. php konvention mukaista, mutta omaan silmään näyttää hyvältä clean codelta. Itse testasin aluksi ohjelmaasi Chrome-selaimella ja tuo dashboardin chart ei toiminut, kokeilin sitten tällä microsoftin uudella Edge-selaimella ja sillä se toimi, joten sitä kannattaa ainakin katsoa vähän :)

SCSS:n käyttö on hyvä juttu, kävin vähän katsomassa sun omia sivuja ja sen perusteella ei tule yllätyksenä että käytät sitä, meinaan webdesign hommia olet näemmä tehnyt työksesi :)

Itselläni on myös tarkoituksena käyttää omassa projektissani Grunttia, joten jos jotain neuvoa voisin siihen antaa, niin kannattaa sillä ainakin minifoida (ja ehkä concatenoida) kaikki sun javascriptit buildin yhteydessä niin saat muutamia bittejä pois ja latausajat nopeutuu vähän :). Voisi myös ehkä olla ihan järkevää käyttää noiden ulkopuolisten librojen/dependencyjen kanssa jotain CDN:ää niin ei tarvii ite hostaa esim kaikkia javascript libroja mitä aiot käyttää. Helppo vaan esittää sun base.html:ssä esim näin https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js. Noh teet kuin itse parhaaksi näet :)

Mitään sen suurempia neuvoja en osaa sulle oikein ainakaan tässä vaiheessa antaa koodinsuhteen kun homma näyttää olevan hyvin hanskassa! :)

Keep up good work!

Niko

**Comment by mcela** [comment]
Kiitos hyvästä palautteesta! :+1: 

Dashboardin chartissa käytettävä Chart.js -kirjasto tosiaan on melko buginen. Tuntuu toimivan vähän milloin huvittaa, pitänee kokeilla jotain muuta kirjastoa.

Hyviä vinkkejä myös Gruntin suhteen. Itse tykkään pitää sen mahdollisimman minimaalisena kehitysvaiheessa. Esimerkiksi javascriptiä koodatessa joka muutoksen jälkeen tehtävä minifointi ja vastaava tuntuu aiheuttavan melkoisesti latenssia, eikä minifoinnista saatavia hyötyjäkään vielä tarvitse. Myöhemmin kyllä tarkoituksena virittää build-komento joka suorittaa minifoinnit ja muut.
